/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de06songuyento;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author TrungCH
 */
public class SoNTJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SoNTJPanel
     */
    public SoNTJPanel() {
        initComponents();
    }
    private ArrayList<Number> danhSachNB = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        minText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maxText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valueText = new javax.swing.JTextField();
        ktButton = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();

        jLabel1.setText("Min:");

        jLabel2.setText("Max:");

        jLabel3.setText("Value:");

        ktButton.setText("Khoi Tao");
        ktButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktButtonActionPerformed(evt);
            }
        });

        luuButton.setText("Luu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minText)
                            .addComponent(maxText)
                            .addComponent(valueText, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ktButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(luuButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(minText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(maxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ktButton)
                    .addComponent(luuButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ktButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktButtonActionPerformed
        // TODO add your handling code here:
        boolean accept = false;
        if (minText.getText().isEmpty() || maxText.getText().isEmpty()) {
            thongBao("không để trống thông tin");
        } else {
            int min = 0;
            int max = 0;
            int value = 0;
            try {
                min = Integer.parseInt(minText.getText());
                max = Integer.parseInt(maxText.getText());
                value = Integer.parseInt(valueText.getText());
                accept = true;
            } catch (Exception e) {
            }
            if (accept) {
                if (min > max) {
                    thongBao("min < max");
                } else if (min > value) {
                    thongBao("min < value");
                } else if (value > max) {
                    thongBao("value < max");
                } else {
                    if (Number.kiemTraSoNT(value) == true) {
                        thongBao("Value là số nguyên tố");
                        danhSachNB.add(new Number(min, max, value));
                    } else {
                        thongBao("Value không  là số nguyên tố");
                    }
                }
            }
        }
    }//GEN-LAST:event_ktButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        int value = Integer.parseInt(valueText.getText());
        if (Number.kiemTraSoNT(value) == true) {
            try {
                FileOutputStream fos = new FileOutputStream("D:/songuyento.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(danhSachNB);
                thongBao("Lưu Thành Công");
                oos.close();
                fos.close();
            } catch (Exception e) {
                thongBao("Lưu Không Thành Công");
                e.printStackTrace();
            }
        } else {
            thongBao("Value không  là số nguyên tố");
        }
    }//GEN-LAST:event_luuButtonActionPerformed
    public void thongBao(String a) {
        JOptionPane.showMessageDialog(this, a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton ktButton;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField maxText;
    private javax.swing.JTextField minText;
    private javax.swing.JTextField valueText;
    // End of variables declaration//GEN-END:variables
}
