/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de02kocolythuyet;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author TrungCH
 */
public class QLNVJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLNVJPanel
     */
    public QLNVJPanel() {
        initComponents();
    }
 private ArrayList<NhanVien> danhSachNV = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tenText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nsText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gtBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pbBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lcbText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hslText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tnText = new javax.swing.JTextField();
        themButton = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        jLabel1.setText("HoTen:");

        jLabel2.setText("NgaySinh:");

        jLabel3.setText("DiaChi:");

        jLabel4.setText("GioiTinh:");

        gtBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));

        jLabel5.setText("PhongBan: ");

        pbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiet Ke", "Nhan Su", "R & D", "Kinh Doanh" }));

        jLabel6.setText("LuongCoBan :");

        jLabel7.setText("HeSoLuong: ");

        jLabel8.setText("ThamNien:");

        themButton.setText("Them");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        luuButton.setText("Luu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tenText)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nsText)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dcText)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                            .addComponent(gtBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lcbText)
                        .addComponent(hslText)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tnText, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themButton)
                        .addGap(33, 33, 33)
                        .addComponent(luuButton)
                        .addGap(42, 42, 42)
                        .addComponent(resetButton)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lcbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hslText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themButton)
                    .addComponent(luuButton)
                    .addComponent(resetButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        tenText.setText("");
        dcText.setText("");
        hslText.setText("");
        lcbText.setText("");
        tnText.setText("");
        nsText.setText("");
        gtBox.setSelectedIndex(0);
        pbBox.setSelectedIndex(0);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
       
        boolean accept = false;
        String ten = tenText.getText();
        float hsl = 0;
        float tn = 0;
        float lcb = 0;
        int ns = 0;
        try {
             hsl = Float.parseFloat(hslText.getText());
             tn = Float.parseFloat(tnText.getText());
             lcb = Float.parseFloat(lcbText.getText());
             ns = Integer.parseInt(nsText.getText());
             accept = true;
        } catch (Exception e) {
            thongBao("Sai Format");
        }
        String pb = (String)pbBox.getSelectedItem();
        String dc = dcText.getText();
        String gt = (String)gtBox.getSelectedItem();
        if(accept){
 //String phongBan, float heSoLuong, float thamNien, float luongCB, String hoTen, int ngaySinh, String diaChi, String gioiTinh            
         danhSachNV.add(new NhanVien(pb,hsl,tn,lcb,ten,ns,dc,gt));
         for(NhanVien nv: danhSachNV){
             System.out.println(nv);
         }
        }
    }//GEN-LAST:event_themButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if(danhSachNV.isEmpty()){
         thongBao("Luu Khong Thanh Cong");
        }else{
            try {
                FileOutputStream fos = new FileOutputStream("nhanvien.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(danhSachNV);
                thongBao("Luu Thanh Cong");
                oos.close();
                fos.close();
            } catch (Exception e) {
                thongBao("Luu Khong Thanh Cong");
            }
  
        }
    }//GEN-LAST:event_luuButtonActionPerformed
 
    public void thongBao(String a){
     JOptionPane.showMessageDialog(this,a);
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dcText;
    private javax.swing.JComboBox<String> gtBox;
    private javax.swing.JTextField hslText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lcbText;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField nsText;
    private javax.swing.JComboBox<String> pbBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField tenText;
    private javax.swing.JButton themButton;
    private javax.swing.JTextField tnText;
    // End of variables declaration//GEN-END:variables
}
