/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de02xeploaidiem;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author TrungCH
 */
public class QLSV extends javax.swing.JPanel {

    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
    }
protected ArrayList<SinhVien> danhSachSV = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tenText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nsText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gtBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cnBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dqtText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dhpText = new javax.swing.JTextField();
        themButton = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        jLabel1.setText("HoTen:");

        jLabel2.setText("NgaySinh:");

        jLabel3.setText("DiaChi:");

        jLabel4.setText("GioiTinh:");

        gtBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));

        jLabel5.setText("Chuyen Nghanh:");

        cnBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATTT", "CNTT", "DTVT" }));

        jLabel6.setText("Diem Qua Trinh:");

        jLabel7.setText("Diem Hoc Phan:");

        themButton.setText("Them");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        luuButton.setText("Luu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tenText)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nsText)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dcText)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(gtBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dqtText)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dhpText, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themButton)
                        .addGap(43, 43, 43)
                        .addComponent(luuButton)
                        .addGap(49, 49, 49)
                        .addComponent(resetButton)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dqtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dhpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themButton)
                    .addComponent(luuButton)
                    .addComponent(resetButton))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("D:/sinhvien.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(danhSachSV);
            thongBao("Luu Thanh Cong");
            oos.close();
            fos.close();
        } catch (Exception e) {
            thongBao("Luu Khong Thanh Cong");
        }
    }//GEN-LAST:event_luuButtonActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
         boolean accept = false;
         if (tenText.getText().isEmpty()
                || nsText.getText().isEmpty()
                || dcText.getText().isEmpty()
                || dqtText.getText().isEmpty()
                || dhpText.getText().isEmpty()) {
           thongBao("khong de trong thong tin");
         }else{
        String ten = tenText.getText();
        String ns = nsText.getText();
        String dc = dcText.getText();
        String gt = (String)gtBox.getSelectedItem();
        String cn = (String)cnBox.getSelectedItem();
        float dqt =0;
        float dhp = 0;
        try {
            dqt = Float.parseFloat(dqtText.getText());
            dhp = Float.parseFloat(dhpText.getText());
            accept = true;
        } catch (Exception e) {
            thongBao("Sai Format");
        }
        if(accept){
          danhSachSV.add(new SinhVien(cn, dqt, dhp,ten,ns,dc,gt));
          thongBao("Luu Thanh Cong");
          for(SinhVien sv : danhSachSV){
              System.out.println(sv); 
          }
        }
         }
    }//GEN-LAST:event_themButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here
        tenText.setText("");
        nsText.setText("");
        dcText.setText("");
        dqtText.setText("");
        dhpText.setText("");
        gtBox.setSelectedIndex(0);
        cnBox.setSelectedIndex(0);
    }//GEN-LAST:event_resetButtonActionPerformed
public void thongBao(String a){
 JOptionPane.showMessageDialog(this, a);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cnBox;
    private javax.swing.JTextField dcText;
    private javax.swing.JTextField dhpText;
    private javax.swing.JTextField dqtText;
    private javax.swing.JComboBox<String> gtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField nsText;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField tenText;
    private javax.swing.JButton themButton;
    // End of variables declaration//GEN-END:variables
}
