/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de03text;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TrungCH
 */
public class QLNVJPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLNVJPanel
     */
    public QLNVJPanel() {
        initComponents();
    }
 private ArrayList<NhanVien> danhSachNV = new ArrayList<>();
  private ArrayList<NhanVien> danhSachNVDoc = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tenText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nsText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gtBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pbBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lcbText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hslText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tnText = new javax.swing.JTextField();
        themButton = new javax.swing.JButton();
        luuButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        htButton = new javax.swing.JButton();

        jLabel1.setText("HoTen:");

        jLabel2.setText("NgaySinh:");

        jLabel3.setText("DiaChi:");

        jLabel4.setText("GioiTinh:");

        gtBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu" }));

        jLabel5.setText("PhongBan: ");

        pbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiet Ke", "Nhan Su", "R & D", "Kinh Doanh" }));

        jLabel6.setText("LuongCoBan :");

        jLabel7.setText("HeSoLuong: ");

        jLabel8.setText("ThamNien:");

        themButton.setText("Them");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        luuButton.setText("Luu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        htButton.setText("HienThi");
        htButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nsText)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcText)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pbBox, 0, 93, Short.MAX_VALUE)
                    .addComponent(gtBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcbText)
                    .addComponent(hslText)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnText, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themButton)
                        .addGap(18, 18, 18)
                        .addComponent(luuButton)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(htButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hslText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themButton)
                            .addComponent(luuButton)
                            .addComponent(resetButton)
                            .addComponent(htButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        tenText.setText("");
        dcText.setText("");
        hslText.setText("");
        lcbText.setText("");
        tnText.setText("");
        nsText.setText("");
        gtBox.setSelectedIndex(0);
        pbBox.setSelectedIndex(0);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
        boolean accept = false;
        String ten = tenText.getText();
        float hsl = 0;
        float tn = 0;
        float lcb = 0;
        int ns = 0;
        try {
             hsl = Float.parseFloat(hslText.getText().trim());
             tn = Float.parseFloat(tnText.getText().trim());
             lcb = Float.parseFloat(lcbText.getText().trim());
             ns = Integer.parseInt(nsText.getText().trim());
             accept = true;
        } catch (Exception e) {
            thongBao("Sai Format");
        }
        String pb = (String)pbBox.getSelectedItem();
        String dc = dcText.getText();
        String gt = (String)gtBox.getSelectedItem();
        if(tenText.getText().trim().isEmpty()
           || nsText.getText().trim().isEmpty()
           || dcText.getText().trim().isEmpty()
           || gtBox.getSelectedItem().toString().trim().isEmpty()
           || pbBox.getSelectedItem().toString().trim().isEmpty()
           ||lcbText.getText().trim().isEmpty()   
           || hslText.getText().trim().isEmpty()  
           ||tnText.getText().trim().isEmpty()){
         thongBao("Khong de trong thong tin");
        }else{
          if(accept){            
         danhSachNV.add(new NhanVien(pb,hsl,tn,lcb,ten,ns,dc,gt));
         thongBao("Them Thanh Cong");
        }else{
         thongBao("Loi Dang Nhap");
        }
        }
    }//GEN-LAST:event_themButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if(danhSachNV.isEmpty()){
         thongBao("Luu Khong Thanh Cong");
        }else{
            try {
                FileOutputStream fos = new FileOutputStream("D:/nhanvien02.dat");
                OutputStreamWriter osw = new  OutputStreamWriter(fos,"UTF-8");
                BufferedWriter bw = new BufferedWriter(osw);
                for(NhanVien nv : danhSachNV){
                 //String phongBan, float heSoLuong, float thamNien, float luongCB, String hoTen, int ngaySinh, String diaChi, String gioiTinh   
                    bw.write(nv.getPhongBan()+"$"+Float.toString(nv.getHeSoLuong())+"$"+Float.toString(nv.getThamNien())+"$"+Float.toString(nv.getLuongCB())+"$"+nv.getHoTen()+"$"+nv.getNgaySinh()+"$"+nv.getDiaChi()+"$"+nv.getGioiTinh());
                    bw.newLine();
                }
                thongBao("Luu Thanh Cong");
                bw.close();
                osw.close();
                fos.close();
            } catch (Exception e) {
                thongBao("Luu Khong Thanh Cong");
            }
         
        }
    }//GEN-LAST:event_luuButtonActionPerformed

    private void htButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("D:/nhanvien02.dat");
            InputStreamReader isr = new InputStreamReader(fis,"UTF-8");
            BufferedReader br = new BufferedReader(isr);
            String line = br.readLine();
            while(line != null){
                String [] thongTin = line.split("\\$");
                NhanVien nv = new NhanVien(thongTin[0],
                                                                   Float.parseFloat(thongTin[1]),
                                                                   Float.parseFloat(thongTin[2]),
                                                                   Float.parseFloat(thongTin[3]),
                                                                   thongTin[4],
                                                                   Integer.parseInt(thongTin[5]),
                                                                   thongTin[6],
                                                                   thongTin[7]);
                danhSachNVDoc.add(nv);
                line = br.readLine();
                }
            br.close();
            isr.close();
            fis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        String[] cot = new String[]{"HoTen","NgaySinh","DiaChi","GioiTinh","PhongBan","LuongCoBan","HeSoLuong","ThamNien","LuongThucLinh"};
        String [][] duuLieu = new String[danhSachNVDoc.size()][];
        for(int i = 0;i<danhSachNVDoc.size();i++){
          NhanVien temp = danhSachNVDoc.get(i);
          duuLieu[i] = new String[]{temp.getHoTen(),Integer.toString(temp.getNgaySinh()),temp.getDiaChi(),
                                                   temp.getGioiTinh(),temp.getPhongBan(),Float.toString(temp.getLuongCB()),
                                                   Float.toString(temp.getHeSoLuong()),Float.toString(temp.getThamNien()),
                                                    Double.toString(temp.luongThucLinh(temp.getLuongCB(), temp.getHeSoLuong(),temp.getThamNien()))};
        }
        DefaultTableModel m = new DefaultTableModel(duuLieu,cot);
        table.setModel(m);
    }//GEN-LAST:event_htButtonActionPerformed
   
    public void thongBao(String a){
     JOptionPane.showMessageDialog(this,a);
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dcText;
    private javax.swing.JComboBox<String> gtBox;
    private javax.swing.JTextField hslText;
    private javax.swing.JButton htButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lcbText;
    private javax.swing.JButton luuButton;
    private javax.swing.JTextField nsText;
    private javax.swing.JComboBox<String> pbBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable table;
    private javax.swing.JTextField tenText;
    private javax.swing.JButton themButton;
    private javax.swing.JTextField tnText;
    // End of variables declaration//GEN-END:variables
}
