/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de01hanghoa;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TrungCH
 */
public class QLHHJPanel extends javax.swing.JPanel {
public ArrayList<DienThoai> danhSachDT = new ArrayList<>();
DefaultTableModel model;
    /**
     * Creates new form QLHHJPanel
     */
    public QLHHJPanel() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tenText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        giaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nhaSXText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dLText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mauText = new javax.swing.JTextField();
        themButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        luuTButton = new javax.swing.JButton();
        luuOButton = new javax.swing.JButton();
        docTButton = new javax.swing.JButton();
        docOButton = new javax.swing.JButton();
        htButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel1.setText("TenHang:");

        jLabel2.setText("MaHang:");

        jLabel3.setText("GiaBan:");

        jLabel4.setText("NhaSX:");

        jLabel5.setText("DungLuongBo Nho: ");

        jLabel6.setText("MauSac:");

        themButton.setText("Them");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        luuTButton.setText("LuuText");
        luuTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuTButtonActionPerformed(evt);
            }
        });

        luuOButton.setText("LuuObject");
        luuOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuOButtonActionPerformed(evt);
            }
        });

        docTButton.setText("DocText");
        docTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docTButtonActionPerformed(evt);
            }
        });

        docOButton.setText("DocObject");
        docOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docOButtonActionPerformed(evt);
            }
        });

        htButton.setText("HienThi");
        htButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenText)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maText)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaText)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nhaSXText)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dLText)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mauText, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(docTButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(luuTButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(themButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(luuOButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(docOButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(90, 90, 90))))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(htButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(giaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhaSXText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dLText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mauText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themButton)
                    .addComponent(resetButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luuTButton)
                    .addComponent(luuOButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docTButton)
                    .addComponent(docOButton))
                .addGap(18, 18, 18)
                .addComponent(htButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
         if(tenText.getText().trim().isEmpty() || nhaSXText.getText().trim().isEmpty() || giaText.getText().trim().isEmpty()
            || maText.getText().trim().isEmpty() || dLText.getText().trim().isEmpty() || mauText.getText().trim().isEmpty()){
                 thongBao("Khong De Trong Thong Tin");
         }else{
        boolean accept = false;
        String nhaSX = nhaSXText.getText();
        String dl = dLText.getText();
        String mau = mauText.getText();
        String ma = maText.getText();
        String ten = tenText.getText();
        float gb = 0;
        try {
            gb = Float.parseFloat(giaText.getText());
            accept = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(accept){    //String nhaSX, String dungLuongBN, String mauSac, String maHang, String tenHang, float giaBan
          danhSachDT.add(new DienThoai(nhaSX,dl,mau,ma,ten,gb));
          thongBao("Them Thanh Cong");
//          for(DienThoai dt : danhSachDT){
//              System.out.println(dt);
//          }
        }else{
           thongBao("Them Khong Thanh Cong");
        }
         }
    }//GEN-LAST:event_themButtonActionPerformed

    private void luuTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuTButtonActionPerformed
        
        try {
            FileOutputStream fos = new FileOutputStream("D:/dienthoaiText.txt");
            OutputStreamWriter osw = new OutputStreamWriter(fos,"UTF-8");
            BufferedWriter bw = new BufferedWriter(osw);
            for (int i = 0; i < danhSachDT.size(); i++) {
                DienThoai dt = danhSachDT.get(i);
                              bw.write(dt.getNhaSX()+"$"+dt.getDungLuongBN()+"$"+dt.getMauSac()+"$"
                             +dt.getMaHang()+"$"+dt.getTenHang()+"$"+dt.getGiaBan());
            }
            thongBao("Luu Thanh Cong");
            bw.close();
            osw.close();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_luuTButtonActionPerformed

    private void luuOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuOButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("D:/dienthoaiObject.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(danhSachDT);
            thongBao("Luu Thanh Cong");
            oos.close();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_luuOButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        tenText.setText("");
        maText.setText("");
        mauText.setText("");
        dLText.setText("");
        nhaSXText.setText("");
        giaText.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void docTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docTButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis= new FileInputStream("D:/dienthoaiText.txt");
            InputStreamReader isr = new InputStreamReader(fis,"UTF-8");
            BufferedReader br = new BufferedReader(isr);
            String line = br.readLine();
            while(line!= null){
                String[] thongTin = line.split("\\$");
                DienThoai dt = new DienThoai(thongTin[0],thongTin[1],thongTin[2],thongTin[3],thongTin[4],Float.parseFloat(thongTin[5]));
                danhSachDT.add(dt);
                line = br.readLine();
            }
//            for(DienThoai temp : danhSachDT){
//                System.out.println(temp);
//            }
            br.close();
            isr.close();
            fis.close();
        } catch (Exception e) {
             e.printStackTrace();
        }
    }//GEN-LAST:event_docTButtonActionPerformed

    private void docOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docOButtonActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("D:/dienthoaiObject.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            danhSachDT = (ArrayList)ois.readObject();
//            for(HangHoa dt : danhSachDT){
//                System.out.println(dt);
//            }
            ois.close();
            fis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_docOButtonActionPerformed

    private void htButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htButtonActionPerformed
        // TODO add your handling code here:
        HienThiThongTin ht = new HienThiThongTin();
        ht.setChuaData(this);
        ht.showKQ();
        JFrame f = new JFrame("Thong Tin Hang Hoa");
        f.add(ht);
        f.pack();
        f.setVisible(true);
        f.setDefaultCloseOperation(3);
    }//GEN-LAST:event_htButtonActionPerformed
public void thongBao(String a){
 JOptionPane.showMessageDialog(this, a);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dLText;
    private javax.swing.JButton docOButton;
    private javax.swing.JButton docTButton;
    private javax.swing.JTextField giaText;
    private javax.swing.JButton htButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton luuOButton;
    private javax.swing.JButton luuTButton;
    private javax.swing.JTextField maText;
    private javax.swing.JTextField mauText;
    private javax.swing.JTextField nhaSXText;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField tenText;
    private javax.swing.JButton themButton;
    // End of variables declaration//GEN-END:variables
}
