/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de06;

/**
 *
 * @author TrungCH
 */
public class TuDienPanel extends javax.swing.JPanel {

    /**
     * Creates new form TuDienPanel
     */
    public TuDienPanel() {
        initComponents();
        yesButton.setVisible(false);
        noButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enField = new javax.swing.JTextField();
        vnField = new javax.swing.JTextField();
        timButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelLoi = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        labelLoi2 = new javax.swing.JLabel();
        themButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Từ Điển");

        jLabel3.setText("EN");

        jLabel4.setText("VN");

        enField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enFieldFocusGained(evt);
            }
        });
        enField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enFieldActionPerformed(evt);
            }
        });

        vnField.setEditable(false);
        vnField.setBackground(new java.awt.Color(255, 255, 255));
        vnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnFieldActionPerformed(evt);
            }
        });

        timButton.setBackground(new java.awt.Color(0, 204, 0));
        timButton.setText("Tìm");
        timButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timButtonActionPerformed(evt);
            }
        });

        labelLoi.setForeground(new java.awt.Color(255, 0, 51));

        yesButton.setBackground(new java.awt.Color(255, 255, 0));
        yesButton.setForeground(new java.awt.Color(0, 0, 0));
        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setBackground(new java.awt.Color(255, 0, 0));
        noButton.setForeground(new java.awt.Color(0, 0, 0));
        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        labelLoi2.setForeground(new java.awt.Color(51, 51, 255));

        themButton.setBackground(new java.awt.Color(0, 153, 51));
        themButton.setText("Thêm");
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timButton)
                        .addGap(18, 18, 18)
                        .addComponent(themButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yesButton)
                        .addGap(18, 18, 18)
                        .addComponent(noButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelLoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(vnField)))
                            .addComponent(labelLoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(enField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(vnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timButton)
                    .addComponent(themButton))
                .addGap(18, 18, 18)
                .addComponent(labelLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelLoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnFieldActionPerformed

    private void enFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enFieldActionPerformed
        
    }//GEN-LAST:event_enFieldActionPerformed

    private void timButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timButtonActionPerformed
        if (enField.getText().equals("")) {
            labelLoi.setText("Chưa nhập từ");
        } else {
            vnField.setText(d.timKiem(enField.getText()));
            if (vnField.getText().equals("")) {
                labelLoi.setText("Từ không có trong từ điển");
                labelLoi2.setText("Bạn có muốn thêm từ???");
                yesButton.setVisible(true);
                noButton.setVisible(true);
            }
        }
    }//GEN-LAST:event_timButtonActionPerformed

    private void enFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enFieldFocusGained
      reset();
    }//GEN-LAST:event_enFieldFocusGained

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
       vnField.setEditable(true);
       themButton.setVisible(true);
       vnField.setText(vnField.getText());
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        reset();
    }//GEN-LAST:event_noButtonActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        d.getDanhSachCacTu().add(new Word(d.getDanhSachCacTu().size()+1,enField.getText(),vnField.getText()));
        reset();
    }//GEN-LAST:event_themButtonActionPerformed
   
    private void reset(){
    vnField.setText("");
    enField.setText("");
    themButton.setVisible(false);
    labelLoi.setText("");
    labelLoi2.setText("");
    yesButton.setVisible(false);
    noButton.setVisible(false);
     vnField.setEditable(false);
    }
    
    private Dictionary d = new Dictionary(Dictionary.TU_KHOI_TAO);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelLoi;
    private javax.swing.JLabel labelLoi2;
    private javax.swing.JButton noButton;
    private javax.swing.JButton themButton;
    private javax.swing.JButton timButton;
    private javax.swing.JTextField vnField;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
